export './src/merlmovie_client.dart';
export './src/widgets/builder.dart';
export './src/global/global.vars.dart';
export './src/models/plugin.dart';
export './src/models/direct_link.dart';
export './src/models/embed.dart';
export './src/helpers/logger.dart';
export './src/providers/browser.dart';
export './src/widgets/prompt_dialog.dart';
export './src/widgets/webview.dart';
export './src/widgets/webview_player.dart';
export './src/widgets/player.dart';
export './src/models/player_callback.dart';
export './src/models/movie.dart';
export './src/helpers/proxy.dart';
export 'package:wakelock_plus/wakelock_plus.dart' show WakelockPlus;
export 'package:provider/provider.dart' show ChangeNotifierProvider;
export 'package:flutter_auto_admob/flutter_auto_admob.dart' show AutoAdmobConfig;
